name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Set PYTHONPATH for all steps
      run: echo "PYTHONPATH=$(pwd)/emtools_mvp:$PYTHONPATH" >> $GITHUB_ENV

    - name: Print PYTHONPATH for debugging
      run: echo "PYTHONPATH=$PYTHONPATH"

    - name: Clear __pycache__
      run: |
        find . -name "*.pyc" -exec rm -f {} \;

    - name: Run tests with coverage
      run: |
        pytest --cov=emtools_mvp --cov-report xml:reports/coverage.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: reports/coverage.xml
        fail_ci_if_error: true

    - name: Lint with ruff
      run: |
        ruff check .

    - name: Complete job
      run: echo "Build and tests complete."
